import { useEffect, useMemo, useState } from 'react';
import { Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { AlertTriangle, BarChart3, BookOpen, Check, ChevronRight, CircleHelp, Cloud, FileAudio, FolderKanban, Gauge, LockKeyhole, LogOut, MessageSquare, Pause, Play, Search, Settings, ShieldCheck, SkipBack, SkipForward, Sparkles, Tags, Users, Wifi } from 'lucide-react';
import { roleLabels, users } from './data';
import { useAppStore } from './store';
import type { DemoUser, Role, Segment } from './types';

const time = (value:number) => `${Math.floor(value/60)}:${String(Math.floor(value%60)).padStart(2,'0')}.${String(Math.round(value%1*100)).padStart(2,'0')}`;

function Login() {
  const login=useAppStore(s=>s.login); const nav=useNavigate(); const [role,setRole]=useState<Role>('annotator'); const selected=users.find(u=>u.role===role)!;
  const submit=(event:React.FormEvent)=>{event.preventDefault();login(selected);nav('/projects')};
  return <main className="login-shell"><section className="brand-panel"><div className="brand"><span className="brand-mark">P</span><span>PurrScription</span></div><div><p className="eyebrow">Collaborative audio workspace</p><h1>Слышать детали.<br/>Сохранять контекст.</h1><p className="lead">Профессиональная среда для разметки, проверки и выпуска речевых данных.</p></div><div className="signal"><span/><span/><span/><span/><span/><span/><span/></div></section><section className="login-panel"><form onSubmit={submit} className="login-form"><p className="eyebrow">Демонстрационный контур</p><h2>Войти в рабочее пространство</h2><p className="muted">Выберите роль — данные аккаунта подставятся автоматически.</p><label>Роль<select value={role} onChange={e=>setRole(e.target.value as Role)}>{users.map(u=><option key={u.role} value={u.role}>{roleLabels[u.role]}</option>)}</select></label><label>Почта<input value={selected.email} readOnly/></label><label>Пароль<input value="demo123" type="password" readOnly/></label><button className="primary" type="submit">Продолжить <ChevronRight size={17}/></button><p className="helper"><ShieldCheck size={15}/> Демо-данные изолированы от production</p></form></section></main>
}

const navItems=[['Проекты',FolderKanban],['Задачи',FileAudio],['Термины',Tags],['Аналитика',BarChart3],['Администрирование',Settings]] as const;
function Shell({children,active='Проекты'}:{children:React.ReactNode;active?:string}) { const user=useAppStore(s=>s.user); const logout=useAppStore(s=>s.logout); const nav=useNavigate(); if(!user)return <Navigate to="/login" replace/>; return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">P</span><span>PurrScription</span></div><nav>{navItems.map(([label,Icon])=><button key={label} className={label===active?'active':''} onClick={()=>label==='Проекты'&&nav('/projects')} disabled={label==='Администрирование'&&user.role!=='admin'} title={label==='Администрирование'&&user.role!=='admin'?'Доступно только администратору':''}><Icon size={18}/>{label}</button>)}</nav><div className="account"><div className="avatar">{user.name.slice(0,1)}</div><div><b>{user.name}</b><small>{roleLabels[user.role]}</small></div><button aria-label="Выйти" onClick={()=>{logout();nav('/login')}}><LogOut size={17}/></button></div></aside>{children}</div> }

function Projects(){const nav=useNavigate();return <Shell><main className="page"><header className="page-head"><div><p className="eyebrow">Рабочий контур</p><h1>Проекты</h1><p className="muted">3 активных проекта · обновлено минуту назад</p></div><button className="primary">Создать проект</button></header><section className="metric-strip"><div><small>В работе</small><strong>18</strong><span>задач</span></div><div><small>На проверке</small><strong>7</strong><span>фрагментов</span></div><div><small>Среднее качество</small><strong>86.4</strong><span>из 100</span></div><div><small>Онлайн</small><strong>5</strong><span>участников</span></div></section><section className="project-list"><div className="section-row"><h2>Недавние проекты</h2><button className="ghost"><Search size={16}/> Найти</button></div>{[['Исследование сервиса поддержки','24 записи · 71% завершено','7 задач'],['Интервью пользователей · Q2','16 записей · 48% завершено','4 задачи'],['Контроль качества колл-центра','32 записи · 89% завершено','11 задач']].map((p,i)=><button className="project-row" key={p[0]} onClick={()=>nav('/tasks')}><span className={`project-glyph g${i}`}>0{i+1}</span><span><b>{p[0]}</b><small>{p[1]}</small></span><span className="project-meta">{p[2]}</span><ChevronRight size={18}/></button>)}</section></main></Shell>}

function Tasks(){const nav=useNavigate();return <Shell active="Задачи"><main className="page"><header className="page-head"><div><p className="eyebrow">Исследование сервиса поддержки</p><h1>Задачи</h1><p className="muted">Фильтр: назначено мне · 6 результатов</p></div><button className="primary">Импортировать запись</button></header><div className="filters"><button className="chip active">Все · 18</button><button className="chip">В работе · 6</button><button className="chip">Проверка · 4</button><button className="chip">Готово · 8</button><div className="search"><Search size={16}/><input placeholder="Поиск по задачам"/></div></div><section className="task-table"><div className="table-head"><span>Запись</span><span>Статус</span><span>Исполнитель</span><span>Качество</span><span/></div><button className="task-row" onClick={()=>nav('/tasks/demo/workspace')}><span><FileAudio size={18}/><span><b>Интервью 014 · Анна</b><small>08:12 · обновлено 2 мин назад</small></span></span><span><i className="status-dot"/>В работе</span><span>Мария Крылова</span><span><b>82.6</b> / 100</span><ChevronRight size={18}/></button>{['Интервью 013 · Михаил','Интервью 011 · Сергей','Интервью 008 · Ольга'].map((name,i)=><button className="task-row" key={name}><span><FileAudio size={18}/><span><b>{name}</b><small>0{6+i}:4{2+i} · вчера</small></span></span><span>{i===1?'На проверке':'Назначено'}</span><span>{i===1?'Ирина Волкова':'Мария Крылова'}</span><span><b>{[91.2,76.8,88.1][i]}</b> / 100</span><ChevronRight size={18}/></button>)}</section></main></Shell>}

function SegmentList(){const segments=useAppStore(s=>s.segments), active=useAppStore(s=>s.activeId), select=useAppStore(s=>s.select);const[query,setQuery]=useState('');const shown=segments.filter(s=>s.text.toLowerCase().includes(query.toLowerCase())||s.id.includes(query));return <aside className="segments-pane"><div className="pane-title"><div><h2>Сегменты</h2><span>{segments.length}</span></div><button title="Справка"><CircleHelp size={17}/></button></div><label className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Текст или номер"/></label><div className="segment-list">{shown.length?shown.map((s,i)=><button key={s.id} className={`segment-item ${active===s.id?'active':''} ${s.confidence<.7?'low':''}`} onClick={()=>select(s.id)}><span className="segment-index">{String(i+1).padStart(2,'0')}</span><span><span className="segment-time">{time(s.start)} — {time(s.end)}</span><b>{s.text||'Нет текста'}</b><small>{s.speaker} · {Math.round(s.confidence*100)}%{s.lockedBy&&<><LockKeyhole size={12}/> {s.lockedBy}</>}</small></span></button>):<div className="empty">Ничего не найдено</div>}</div></aside>}

function Waveform(){const segments=useAppStore(s=>s.segments),active=useAppStore(s=>s.activeId),select=useAppStore(s=>s.select),current=useAppStore(s=>s.currentTime),setTime=useAppStore(s=>s.setTime);return <div className="wave-wrap"><div className="wave-toolbar"><span>Дорожка 1 · interview_014.wav</span><span>48 kHz · mono</span></div><div className="wave" onClick={e=>setTime(e.nativeEvent.offsetX/e.currentTarget.clientWidth*82)}>{Array.from({length:120},(_,i)=><i key={i} style={{height:`${16+((i*17)%43)}%`}}/>)}{segments.map(s=><button aria-label={`Сегмент ${s.id}`} key={s.id} onClick={e=>{e.stopPropagation();select(s.id)}} className={`region ${active===s.id?'active':''} ${s.confidence<.7?'low':''}`} style={{left:`${s.start/82*100}%`,width:`${(s.end-s.start)/82*100}%`}}/>)}<span className="playhead" style={{left:`${current/82*100}%`}}/></div><div className="timeline">{[0,10,20,30,40,50,60,70,80].map(v=><span key={v} style={{left:`${v/82*100}%`}}>{v}s</span>)}</div><div className="minimap">{Array.from({length:80},(_,i)=><i key={i} style={{height:`${20+((i*11)%60)}%`}}/>)}<span style={{width:'34%',left:'6%'}}/></div></div>}

function Player(){const playing=useAppStore(s=>s.playing),setPlaying=useAppStore(s=>s.setPlaying),segmentMode=useAppStore(s=>s.segmentMode),setSegmentMode=useAppStore(s=>s.setSegmentMode),speed=useAppStore(s=>s.speed),setSpeed=useAppStore(s=>s.setSpeed),current=useAppStore(s=>s.currentTime),setTime=useAppStore(s=>s.setTime),segments=useAppStore(s=>s.segments),activeId=useAppStore(s=>s.activeId);const active=segments.find(s=>s.id===activeId)!;useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setTime(Math.min(segmentMode?active.end:82,current+.1*speed)),100);return()=>clearInterval(timer)},[playing,current,speed,segmentMode,active,setTime]);useEffect(()=>{if(segmentMode&&current>=active.end)setPlaying(false)},[current,active,segmentMode,setPlaying]);return <div className="player"><button onClick={()=>setTime(Math.max(0,current-1))}><SkipBack size={18}/></button><button className="play" onClick={()=>{if(segmentMode&&current>=active.end)setTime(active.start);setPlaying(!playing)}}>{playing?<Pause size={21}/>:<Play size={21}/>}</button><button onClick={()=>setTime(Math.min(82,current+1))}><SkipForward size={18}/></button><strong>{time(current)}</strong><span className="divider"/><button className={segmentMode?'mode-on':''} onClick={()=>{setSegmentMode(true);setTime(active.start);setPlaying(true)}}>Играть сегмент</button><label>Скорость<select value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[.5,.75,1,1.25,1.5,2].map(v=><option key={v}>{v}</option>)}</select></label><span className="keyhint">Space</span></div>}

function Editor(){const segments=useAppStore(s=>s.segments),activeId=useAppStore(s=>s.activeId),update=useAppStore(s=>s.updateSegment),user=useAppStore(s=>s.user);const source=segments.find(s=>s.id===activeId)!;const[draft,setDraft]=useState<Segment>(source);useEffect(()=>setDraft(source),[source]);const readonly=user?.role==='customer'||user?.role==='ml_engineer'||Boolean(source.lockedBy);return <section className="editor"><div className="editor-head"><span><b>Сегмент {source.id.replace('seg-','')}</b><small>Версия 4 · сохранено</small></span>{source.confidence<.7&&<span className="warning"><AlertTriangle size={15}/> Низкая уверенность {Math.round(source.confidence*100)}%</span>}</div><textarea aria-label="Текст сегмента" value={draft.text} disabled={readonly} onChange={e=>setDraft({...draft,text:e.target.value})}/><div className="fields"><label>Начало<input type="number" step="0.01" disabled={readonly} value={draft.start} onChange={e=>setDraft({...draft,start:Number(e.target.value)})}/></label><label>Конец<input type="number" step="0.01" disabled={readonly} value={draft.end} onChange={e=>setDraft({...draft,end:Number(e.target.value)})}/></label><label>Спикер<select disabled={readonly} value={draft.speaker} onChange={e=>setDraft({...draft,speaker:e.target.value as Segment['speaker']})}>{['TATLIN','VEGMAN','[CROSSTALK]','[OVERLAP]','[SILENCE]'].map(s=><option key={s}>{s}</option>)}</select></label><div className="editor-actions">{readonly?<span className="lock-note"><LockKeyhole size={14}/>{source.lockedBy?`Редактирует ${source.lockedBy}`:'Только чтение для вашей роли'}</span>:<><button className="ghost">Разделить</button><button className="primary" onClick={()=>update(draft)}><Check size={16}/>Сохранить</button></>}</div></div></section>}

function Inspector(){const markers=useAppStore(s=>s.markers),select=useAppStore(s=>s.select);const[t,setT]=useState('problems');return <aside className="inspector"><div className="tabs">{[['problems','Проблемы'],['comments','Комментарии'],['history','История']].map(([id,label])=><button key={id} className={t===id?'active':''} onClick={()=>setT(id)}>{label}</button>)}</div>{t==='problems'&&<><div className="quality"><div><Gauge size={20}/><span><b>82.6</b><small>Quality Score</small></span></div><span className="score-badge">−3.4</span></div><div className="gate"><h3>Quality Gate</h3><p><AlertTriangle size={15}/> 1 блокирующая проблема</p><p><Sparkles size={15}/> 3 предупреждения</p><button className="primary" disabled title="Сначала исправьте критические маркеры">Отправить на проверку</button><small>Недоступно: открыт критический маркер</small></div><div className="issues"><h3>Открытые маркеры</h3>{markers.map(m=><button key={m.id} onClick={()=>select(m.segmentId)}><i className={m.severity}/><span><b>{m.title}</b><small>{m.segmentId} · {m.status}</small></span><ChevronRight size={16}/></button>)}</div></>}{t==='comments'&&<div className="thread"><h3>Обсуждение</h3><p><b>Ирина Волкова</b><small> 5 минут назад</small></p><p>Проверьте переход между спикерами на 00:18.</p><button className="ghost"><MessageSquare size={15}/>Ответить</button></div>}{t==='history'&&<div className="thread"><h3>Последние изменения</h3><p><b>Мария Крылова</b></p><p>Обновила текст сегмента 002</p><small>Сегодня, 14:32</small></div>}</aside>}

function Workspace(){const user=useAppStore(s=>s.user);const playing=useAppStore(s=>s.playing),setPlaying=useAppStore(s=>s.setPlaying),segments=useAppStore(s=>s.segments),active=useAppStore(s=>s.activeId),select=useAppStore(s=>s.select),setTime=useAppStore(s=>s.setTime),setMode=useAppStore(s=>s.setSegmentMode);useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('textarea,input,select'))return;if(e.code==='Space'){e.preventDefault();setPlaying(!playing)}if(e.key==='Escape'){setPlaying(false);setMode(false)}if(e.key==='ArrowDown'||e.key==='ArrowRight'){e.preventDefault();const i=segments.findIndex(s=>s.id===active);const next=segments[Math.min(segments.length-1,i+1)];select(next.id);setTime(next.start)}if(e.key==='ArrowUp'||e.key==='ArrowLeft'){e.preventDefault();const i=segments.findIndex(s=>s.id===active);const prev=segments[Math.max(0,i-1)];select(prev.id);setTime(prev.start)}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[playing,setPlaying,segments,active,select,setTime,setMode]);if(!user)return <Navigate to="/login" replace/>;return <div className="workspace"><header className="workspace-head"><div className="brand"><span className="brand-mark">P</span></div><div className="crumb">Проекты <ChevronRight size={14}/> Интервью Q2 <ChevronRight size={14}/><b>Интервью 014</b></div><span className="status"><i/>В работе</span><div className="presence"><span title="Мария Крылова">МК</span><span title="Ирина Волкова">ИВ</span><span title="Алексей Минин">АМ</span><small>+2</small></div><div className="connection"><Wifi size={15}/> Онлайн</div><div className="autosave"><Cloud size={15}/> Сохранено</div><div className="head-score"><Gauge size={17}/><b>82.6</b></div></header><div className="workspace-grid"><SegmentList/><main className="stage"><Waveform/><Player/><Editor/></main><Inspector/></div></div>}

export function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/projects" element={<Projects/>}/><Route path="/tasks" element={<Tasks/>}/><Route path="/tasks/:id/workspace" element={<Workspace/>}/><Route path="*" element={<Navigate to="/login" replace/>}/></Routes>}
