import{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{FastForward,Pause,Play,Plus,Rewind,RotateCcw,Volume2,ZoomIn,ZoomOut}from'lucide-react';
import WaveSurfer from'wavesurfer.js';import Hover from'wavesurfer.js/dist/plugins/hover.esm.js';import Minimap from'wavesurfer.js/dist/plugins/minimap.esm.js';import Regions from'wavesurfer.js/dist/plugins/regions.esm.js';import Timeline from'wavesurfer.js/dist/plugins/timeline.esm.js';import Zoom from'wavesurfer.js/dist/plugins/zoom.esm.js';
import{mediaFetchParams,mediaUrl}from'./api';import{speakerColor,speakerInitials}from'./speaker';import type{Segment}from'./types';

const formatTime=(value:number)=>{const centiseconds=Math.max(0,Math.round(value*100)),minutes=Math.floor(centiseconds/6000),seconds=Math.floor(centiseconds%6000/100),fraction=centiseconds%100;return`${minutes}:${String(seconds).padStart(2,'0')}.${String(fraction).padStart(2,'0')}`};
interface Props{mediaId:string;mediaName:string;segments:Segment[];activeId:string|null;editable:boolean;onSelect:(id:string)=>void;onBoundaryChange:(id:string,start:number,end:number)=>Promise<void>;onCreate:(start:number,end:number)=>Promise<void>}
export function WaveformEditor({mediaId,mediaName,segments,activeId,editable,onSelect,onBoundaryChange,onCreate}:Props){const container=useRef<HTMLDivElement>(null),wave=useRef<WaveSurfer|null>(null),regions=useRef<Regions|null>(null),segmentRef=useRef(segments),createModeRef=useRef(false),[ready,setReady]=useState(false),[loading,setLoading]=useState(0),[error,setError]=useState(''),[playing,setPlaying]=useState(false),[current,setCurrent]=useState(0),[duration,setDuration]=useState(0),[speed,setSpeed]=useState(1),[volume,setVolume]=useState(1),[zoom,setZoom]=useState(35),[createMode,setCreateMode]=useState(false),[loop,setLoop]=useState(false),[padding,setPadding]=useState(.3),stopAt=useRef<number|null>(null);
  segmentRef.current=segments;createModeRef.current=createMode;
  useEffect(()=>{if(!container.current)return;setError('');setReady(false);const regionPlugin=Regions.create(),instance=WaveSurfer.create({container:container.current,url:mediaUrl(mediaId),fetchParams:mediaFetchParams(),height:260,waveColor:'#b8bab5',progressColor:'#5f625e',cursorColor:'#d27432',cursorWidth:2,normalize:true,minPxPerSec:35,autoCenter:true,autoScroll:true,dragToSeek:true,plugins:[regionPlugin,Timeline.create({height:24,timeInterval:.5,primaryLabelInterval:5,secondaryLabelInterval:1,style:{fontSize:'10px',color:'#6b6d68'}}),Minimap.create({height:46,waveColor:'#c8cac5',progressColor:'#777a75',overlayColor:'rgba(210,116,50,.14)'}),Hover.create({lineColor:'#d27432',lineWidth:1,labelBackground:'#292a28',labelColor:'#fff',labelSize:'10px'}),Zoom.create({scale:.4,maxZoom:500,deltaThreshold:8})]});wave.current=instance;regions.current=regionPlugin;
    const off=[instance.on('loading',value=>setLoading(value)),instance.on('ready',value=>{setDuration(value);setReady(true);setLoading(100)}),instance.on('error',value=>setError(value instanceof Error?value.message:String(value))),instance.on('timeupdate',value=>{setCurrent(value);if(stopAt.current!==null&&value>=stopAt.current){instance.pause();if(loop&&activeId){const segment=segmentRef.current.find(s=>s.id===activeId);if(segment){instance.setTime(Math.max(0,segment.start-padding));instance.play();stopAt.current=Math.min(instance.getDuration(),segment.end+padding)}}else stopAt.current=null}}),instance.on('play',()=>setPlaying(true)),instance.on('pause',()=>setPlaying(false)),instance.on('finish',()=>setPlaying(false)),regionPlugin.on('region-clicked',(region,event)=>{event.stopPropagation();onSelect(region.id);instance.setTime(region.start)}),regionPlugin.on('region-updated',region=>{if(segmentRef.current.some(s=>s.id===region.id))void onBoundaryChange(region.id,Number(region.start.toFixed(2)),Number(region.end.toFixed(2)))}),regionPlugin.on('region-created',region=>{if(createModeRef.current&&!segmentRef.current.some(s=>s.id===region.id)){const start=Number(region.start.toFixed(2)),end=Number(region.end.toFixed(2));region.remove();setCreateMode(false);void onCreate(start,end)}})];
    return()=>{off.forEach(un=>un());instance.destroy();wave.current=null;regions.current=null}
  },[mediaId,onSelect,onBoundaryChange,onCreate,loop,activeId,padding]);
  useEffect(()=>{if(!ready||!regions.current)return;regions.current.clearRegions();segments.forEach(segment=>{const color=speakerColor(segment.speaker),multi=segment.speaker?.includes('+')||segment.speaker==='[CROSSTALK]',content=document.createElement('span');content.className='region-label';content.textContent=speakerInitials(segment.speaker);content.title=segment.speaker||'Без спикера';const region=regions.current!.addRegion({id:segment.id,start:segment.start,end:segment.end,color:multi?`repeating-linear-gradient(135deg,${color.soft} 0 8px,rgba(255,255,255,.2) 8px 14px)`:color.soft,content,drag:editable&&segment.id===activeId,resize:editable&&segment.id===activeId,minLength:.1});if(region.element){region.element.style.borderColor=color.solid;region.element.classList.toggle('selected-region',segment.id===activeId)}})},[segments,activeId,editable,ready]);
  useEffect(()=>{if(!regions.current||!ready||!editable)return;if(!createMode)return;const disable=regions.current.enableDragSelection({color:'rgba(210,116,50,.28)',minLength:.1});return disable},[createMode,editable,ready]);
  useEffect(()=>{wave.current?.setPlaybackRate(speed,true)},[speed]);useEffect(()=>wave.current?.setVolume(volume),[volume]);useEffect(()=>{if(wave.current&&ready)wave.current.zoom(zoom)},[zoom,ready]);
  const active=segments.find(s=>s.id===activeId),speakers=useMemo(()=>Array.from(new Set(segments.map(s=>s.speaker).filter((s):s is string=>Boolean(s)))),[segments]);
  const playSegment=useCallback(()=>{if(!active||!wave.current)return;const start=Math.max(0,active.start-padding);stopAt.current=Math.min(wave.current.getDuration(),active.end+padding);wave.current.setTime(start);void wave.current.play()},[active,padding]);
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{const target=event.target as HTMLElement;if(target.matches('input,textarea,select,button,[contenteditable="true"]'))return;if(event.code==='Space'){event.preventDefault();event.shiftKey?playSegment():wave.current?.playPause()}if(event.key.toLowerCase()==='j'){event.preventDefault();wave.current?.skip(event.shiftKey?-.1:-1)}if(event.key.toLowerCase()==='l'){event.preventDefault();wave.current?.skip(event.shiftKey?.1:1)}if(event.key==='Escape'){wave.current?.stop();stopAt.current=null}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[playSegment]);
  return <section className="waveform-panel" aria-label="Аудиодорожка"><header className="waveform-header"><div><b>{mediaName}</b><small>{ready?`${formatTime(duration)} · реальное медиа`:`Загрузка ${loading}%`}</small></div><div className="speaker-legend" aria-label="Цвета спикеров">{speakers.map(s=>{const c=speakerColor(s);return <span key={s}><i style={{background:c.solid}}/>{s}</span>})}</div></header>{error&&<div className="media-error" role="alert"><b>Аудио недоступно</b><span>{error}. Проверьте, что файл существует в media storage backend.</span></div>}<div className="waveform-canvas" ref={container}/><div className="waveform-controls"><button className="icon-button" aria-label="Назад на одну секунду" onClick={()=>wave.current?.skip(-1)}><Rewind size={18}/></button><button className="play-button" aria-label={playing?'Пауза':'Воспроизвести'} onClick={()=>wave.current?.playPause()} disabled={!ready}>{playing?<Pause size={20}/>:<Play size={20}/>}</button><button className="icon-button" aria-label="Вперёд на одну секунду" onClick={()=>wave.current?.skip(1)}><FastForward size={18}/></button><output>{formatTime(current)} <span>/ {formatTime(duration)}</span></output><button className="button segment-play" onClick={playSegment} disabled={!active||!ready}>Играть сегмент</button><button className={`button ${loop?'active':''}`} aria-pressed={loop} onClick={()=>setLoop(v=>!v)}><RotateCcw size={15}/>Повтор</button><label className="compact-field">Поля<select value={padding} onChange={e=>setPadding(Number(e.target.value))}>{[.3,.5,.75,1].map(v=><option key={v} value={v}>{v} c</option>)}</select></label><label className="compact-field">Скорость<select value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[.5,.75,1,1.25,1.5,2].map(v=><option key={v} value={v}>{v}×</option>)}</select></label><label className="volume"><Volume2 size={16}/><input aria-label="Громкость" type="range" min="0" max="1" step=".05" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></label><button className="icon-button" aria-label="Уменьшить масштаб" onClick={()=>setZoom(v=>Math.max(10,v-20))}><ZoomOut size={17}/></button><button className="icon-button" aria-label="Увеличить масштаб" onClick={()=>setZoom(v=>Math.min(500,v+20))}><ZoomIn size={17}/></button>{editable&&<button className={`button create-region ${createMode?'active':''}`} aria-pressed={createMode} onClick={()=>setCreateMode(v=>!v)}><Plus size={16}/>{createMode?'Выделите диапазон':'Новый сегмент'}</button>}</div></section>}
